version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'backoffice'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'root_password'
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/postgres/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    command: npm run start
    depends_on:
      - db
    ports:
      - "80:3000"
    volumes:
      - .:/usr/src/app

volumes:
  database:
    driver: local